#' Add pagination to a Megamation API request
#' @param req An API request generated by package httr2 or mm_req().
#' @export

mm_req_paginate <- function(req) {
  req |>
    httr2::req_paginate_next_url(
      parse_resp = function(resp) {
        parsed <- resp |>
          httr2::resp_body_raw() |>
          rawToChar() |>
          jsonlite::fromJSON() |>
          purrr::list_flatten()

        parsed$next_page <- if(parsed$next_page == "") NULL else(parsed$next_page)

        list(data = find_data(parsed), next_url = parsed$next_page)
      }
    )
}
