#' Perform a Megamation API request
#' @param req An API request generated by [mm_req()] or [httr2::req()].
#' @export
mm_req_perform <- function(req) {

  if(!is_paginated(req)) {
    req |> httr2::req_perform()
  } else {
    req |> httr2::paginate_req_perform()
  }

}

