#' Add pagination to a Megamation API request
#' @param req An API request generated by package httr2 or mm_req().
#' @export

mm_req_paginate <- function(req) {
  req |>
    httr2::req_paginate_next_url(
      parse_resp = function(resp) {
        parsed <- mm_parse(resp)

        parsed$next_url <- if(parsed$next_page == "") NULL else(parsed$next_page)

        list(data = mm_pluck_data(parsed), next_url = parsed$next_url)
      }
    )
}
