#' Add pagination to a Megamation API request
#' @param req An API request generated by package httr2 or mm_req().
#' @export

mm_req_paginate <- function(req) {
  req |>
    httr2::req_paginate(
      next_request = function(req, parsed) {
        if (parsed$next_page == "") return(NULL)
        req |> req_url(parsed$next_page)
      }
    )
}

#' Add pagination to a Megamation API request
#' @param req An API request generated by package httr2 or mm_req().
#' @export

mm_req_paginate2 <- function(req) {
  req |>
    httr2::req_paginate_next_url(
      parse_resp = function(resp) {
        parsed <- mm_parse(resp)

        parsed$next_url <- if (parsed$next_page == "") {
          NULL
          }
        else (parsed$next_page)

        list(data = mm_keep_df(parsed), next_url = parsed$next_url)
      }
    )
}

#' Perform a paginated request
#' @param req An API request generated by mm_req() with pagination from
#' mm_req_paginate().
#' @param max_pages Max number of pages to request.
#' @export

mm_req_perform_paginate <- function(req, max_pages = NULL) {
  out <- vector("list", purrr::`%||%`(max_pages, 10))
  i <- 1L

  repeat({
    out[[i]] <- req_perform(req) |> mm_parse()
    if (!is.null(max_pages) && i == max_pages) {
      break
    }

    req <- req |> httr2::paginate_next_request(parsed = out[[i]])

    if (is.null(req)) {
      break
    }

    i <- i + 1L
    if (i > length(out)) {
      length(out) <- length(out) * 2L
    }
  })

  if (i != length(out)) {
    out <- out[seq_len(i)]
  }
  out

}
