#' Add pagination to a Megamation API request
#'
#' `mm_req_paginate()` adds pagination to a request based on the next_url given
#' by the parsed response.
#'
#' @param req An API request generated by [mm_request()].
#' @returns An object of class `httr2_request`.
#' @export
#' @examplesIf httr2::secret_has_key("HTTR2_KEY_MEGAMATION")
#' mm_request("workorder") |> mm_req_paginate()
mm_req_paginate <- function(req) {
  check_request(req)
  req |>
    httr2::req_paginate_next_url(
      parse_resp = function(resp) mm_data_and_url(resp),
      n_pages = function(parsed) mm_n_pages(parsed)
    )
}
